FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# requirements.txt liegt im Root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# backend code kopieren
COPY backend/app /app/app
COPY backend/modules /app/modules

EXPOSE 8000

CMD ["uvicorn", "app.quizly:app", "--host", "0.0.0.0", "--port", "8000"]
